linters:
  enable-all: true

  disable:
    # - goerr113
    # - gofumpt        # Prefer `gofmt` rules / some rules conflict with `wsl`
    # - gomnd          # XXX: For now
    - nonamedreturns # I disagree with the rationale behind this linter
    - exhaustivestruct
    # - golint
    # - interfacer 
    # - maligned
    # - scopelint
    # - bodyclose
    - contextcheck
    # - nilerr
    - noctx
    # - rowserrcheck
    # - sqlclosecheck
    # - structcheck
    # - tparallel
    # - unparam
    - wastedassign
    - godot
    - exhaustruct
    - gci

linters-settings:
  lll:
    line-length: 130
  # gci:
  #   no-inline-comments: true
  #   no-prefix-comments: true
  #   sections:
  #     - standard
  #     - default
  #   section-separators:
  #     - newLine
  # ireturn:
  #   allow:
  #     - error
  #     - stdlib
  #     #
  #     - 'go.opentelemetry.io/otel/trace.Span'
  varnamelen:
    max-distance: 10
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-decls:
      - b bytes.Buffer
      - h http.Handler
      - id string
      - ok bool
      - r *http.Request
      - w http.ResponseWriter
issues:
  exclude-rules:
    # Because this is a global logger
    - path: log.go
      linters:
        - gochecknoglobals
        - gochecknoinits
        - ireturn
    # All tests
    - path: _test\.go
      linters:
        - cyclop
        - errchkjson
        - funlen
        - goerr113
        - lll
        - varnamelen
        - wrapcheck
    # Final binaries
    - path: cmd/
      linters:
        - cyclop
        - funlen
        - gocognit
        - unparam
